// Dining Services Monthly In-Service Quizzes
// Content based on the DiningRD 2020 Guideline & Procedure Manual for Long Term Care
// (Health Technologies, Inc.) and the FDA 2017 Food Code.
// Each module: 10 questions, pass = 100%. Staff retake until they pass.

const MODULES = [
  {
    n: 1,
    month: "January",
    title: "Orientation, Resident Rights & Abuse Reporting",
    keyPoints: [
      "Every dining employee must know the community's mission, organizational structure, and employee handbook.",
      "Residents have rights — including the right to be treated with dignity and to refuse a food item.",
      "If a resident refuses a menu item, offer a substitute of similar nutritive value.",
      "If you see or suspect abuse or neglect, report it IMMEDIATELY per your community's policy.",
      "All staff are expected to act honestly, ethically, and fairly at all times.",
      "If you miss a scheduled in-service, you will be rescheduled or given the materials to review."
    ],
    questions: [
      { q: "You see something that might be abuse or neglect of a resident. What should you do?",
        c: ["Wait and see if it happens again", "Report it immediately according to your community's abuse reporting policy", "Only report it if the resident asks you to", "Discuss it with coworkers first"], a: 1 },
      { q: "A resident refuses the entrée on their tray. What should happen?",
        c: ["They just skip that item", "They are told to eat it anyway", "They are offered a substitute of similar nutritive value", "They must wait until the next meal"], a: 2 },
      { q: "Who is expected to understand and demonstrate the community's mission statement?",
        c: ["Only the Administrator", "Only nursing staff", "Only department managers", "Every employee, including dining services staff"], a: 3 },
      { q: "Which of these is a resident right that affects dining services?",
        c: ["Being treated with dignity and having food preferences honored", "Choosing which employees get scheduled", "Setting kitchen cleaning schedules", "Deciding other residents' diets"], a: 0 },
      { q: "What behavior standard applies to all dining services employees?",
        c: ["Honest, ethical, and fair behavior at all times", "Ethics only apply to managers", "Honesty only matters during surveys", "Fairness applies only to residents you know well"], a: 0 },
      { q: "You miss the monthly in-service because you were off that day. What should happen?",
        c: ["You skip that topic for the year", "You are rescheduled or given the materials to review", "Nothing — attendance is optional", "You are automatically written up"], a: 1 },
      { q: "Why is orientation and training documented with your signature?",
        c: ["It's only for payroll purposes", "To show you were trained and are equipped to do your job", "It's optional paperwork", "Only new employees need documentation"], a: 1 },
      { q: "Who directs the day-to-day work of the Dining Services Department?",
        c: ["The Dining Services Manager", "The night shift CNA", "The residents' families", "The delivery driver"], a: 0 },
      { q: "Where can you find the policies and procedures that guide your job in dining services?",
        c: ["There are no written policies", "Only the corporate office has them", "In the department's guideline & procedure manual and employee handbook", "You must memorize them from coworkers"], a: 2 },
      { q: "A visitor asks you for private medical information about a resident. What do you do?",
        c: ["Tell them what you know", "Politely decline and refer them to the nurse — resident information is protected (HIPAA)", "Post the diet list where visitors can see it", "Ask other residents what they know"], a: 1 }
    ]
  },
  {
    n: 2,
    month: "February",
    title: "Personal Hygiene, Handwashing & Glove Use",
    keyPoints: [
      "Scrub hands with soap for 15–20 seconds or more — under nails, between fingers, backs of hands and forearms.",
      "Turn off the faucet with a paper towel, not your clean bare hands.",
      "Wash hands at least every hour, after breaks, between tasks, and before/after handling food.",
      "Hand sanitizer NEVER replaces handwashing — it may only be used after proper handwashing.",
      "Wash hands before putting gloves on AND after taking them off. The rule: wash, glove, remove, rewash, re-glove.",
      "Change gloves any time they touch your face, hair, uniform, or any non-food surface.",
      "Report illness (nausea, vomiting, fever) to your supervisor. Keep cuts and sores covered.",
      "No gum, tobacco, or eating in food preparation or dining areas. Wear hair restraints."
    ],
    questions: [
      { q: "How long should you scrub your hands with soap when washing?",
        c: ["5 seconds", "At least 15–20 seconds", "2 seconds with hot water", "Only until the soap rinses off"], a: 1 },
      { q: "After washing your hands, how should you turn off the faucet?",
        c: ["With your clean bare hand", "With your elbow on any faucet", "With a paper towel", "Leave the water running"], a: 2 },
      { q: "At minimum, how often should dining staff wash their hands during a shift?",
        c: ["Once at the start of shift", "At least every hour, plus between tasks and after breaks", "Only after using the restroom", "Every four hours"], a: 1 },
      { q: "Can hand sanitizer replace handwashing in the kitchen?",
        c: ["Yes, sanitizer works better than soap", "Yes, if you're busy", "No — sanitizer may only be used AFTER proper handwashing, never instead of it", "Only on weekends"], a: 2 },
      { q: "What is the correct glove routine?",
        c: ["Wash hands, put on gloves, remove gloves, rewash, re-glove", "Put gloves on dirty hands — the gloves protect the food", "Wear one pair all shift", "Rinse gloves and reuse them"], a: 0 },
      { q: "You touch your face while wearing gloves during food prep. What now?",
        c: ["Keep working — gloves are still on", "Wipe the gloves on your apron", "Rinse the gloves in the sink", "Remove gloves, wash hands, and put on a new pair"], a: 3 },
      { q: "When are gloves required?",
        c: ["Whenever there is direct contact with food", "Only when handling raw meat", "Only during surveys", "Only when a supervisor is watching"], a: 0 },
      { q: "You wake up with vomiting and a fever on a workday. What should you do?",
        c: ["Come to work and stay away from food", "Report your illness to your supervisor and follow the employee illness policy — don't work with food while ill", "Take medicine and tell no one", "Wear two pairs of gloves"], a: 1 },
      { q: "What should you do with an open cut or sore on your hand?",
        c: ["Leave it uncovered so it heals faster", "Cover it properly (bandage plus glove) and report it", "Ignore it if it's small", "Only cover it when a surveyor visits"], a: 1 },
      { q: "Which of these is allowed in food preparation areas?",
        c: ["Chewing gum", "Eating snacks while cooking", "None of these — no gum, tobacco, or eating in food prep and dining service areas", "Smokeless tobacco"], a: 2 }
    ]
  },
  {
    n: 3,
    month: "March",
    title: "Safe Cooking Temperatures & Thermometer Use",
    keyPoints: [
      "Poultry, stuffed foods, and casseroles: cook to 165°F minimum.",
      "Ground meat, seafood/shellfish, and injected meats (like ham): 155°F minimum.",
      "Fish, pork or beef steaks/chops, and eggs for immediate service: 145°F minimum.",
      "Any food cooked, cooled, and reheated must reach 165°F.",
      "Food cooked or reheated in a microwave: 165°F, then let stand 2 minutes.",
      "Insert a calibrated thermometer into the thickest part of the food and take at least two readings in different places.",
      "Hot foods must be held at 135°F or above; cold foods at 41°F or below."
    ],
    questions: [
      { q: "What is the minimum internal cooking temperature for poultry (chicken, turkey)?",
        c: ["145°F", "155°F", "165°F", "135°F"], a: 2 },
      { q: "What is the minimum internal cooking temperature for ground meat (like hamburger)?",
        c: ["135°F", "155°F", "125°F", "165°F for 4 minutes"], a: 1 },
      { q: "What is the minimum internal cooking temperature for fish?",
        c: ["165°F", "125°F", "155°F", "145°F"], a: 3 },
      { q: "Leftover soup is being reheated for service. What temperature must it reach?",
        c: ["120°F", "135°F", "145°F", "165°F"], a: 3 },
      { q: "Food cooked in the microwave must reach 165°F and then…",
        c: ["Be served immediately", "Stand for 2 minutes after microwaving", "Cool for 10 minutes", "Be stirred once and served"], a: 1 },
      { q: "Where should you insert the thermometer to check a food's temperature?",
        c: ["Into the thickest part, taking at least two readings in different places", "Just under the surface", "Touching the bottom of the pan", "Anywhere — one quick reading is enough"], a: 0 },
      { q: "Casseroles and stuffed foods must reach what minimum internal temperature?",
        c: ["145°F", "155°F", "165°F", "140°F"], a: 2 },
      { q: "What is the minimum HOT holding temperature for foods on the steam table?",
        c: ["110°F", "120°F", "135°F", "165°F"], a: 2 },
      { q: "Cold foods (like salads and cold desserts) must be held at or below…",
        c: ["41°F", "50°F", "60°F", "45°F for everything including salads"], a: 0 },
      { q: "Pork chops and beef steaks must reach what minimum internal temperature?",
        c: ["125°F", "145°F", "165°F", "175°F"], a: 1 }
    ]
  },
  {
    n: 4,
    month: "April",
    title: "Cooling Foods, Holding & Leftovers",
    keyPoints: [
      "Cool foods in two steps: 135°F down to 70°F within 2 hours, then 70°F down to 41°F within the next 4 hours.",
      "If food doesn't reach 70°F within 2 hours: reheat it to 165°F (within 2 hours) or throw it out.",
      "Use shallow containers no more than 4 inches deep. Ice-water baths and ice paddles speed cooling.",
      "Don't put hot food in the refrigerator until it reaches 70°F. Cover loosely while cooling so heat escapes.",
      "Once cooled below 41°F, cover tightly and label with contents and use-by date.",
      "Leftovers in the refrigerator: labeled and dated, use-by date no more than 72 hours from first use.",
      "Hot holding: 135°F or above. Cold holding: 41°F or below (milk below 45°F)."
    ],
    questions: [
      { q: "In the two-step cooling process, hot food must go from 135°F to 70°F within…",
        c: ["30 minutes", "2 hours", "4 hours", "6 hours"], a: 1 },
      { q: "After reaching 70°F, food must cool to 41°F within the next…",
        c: ["1 hour", "2 hours", "4 hours", "8 hours"], a: 2 },
      { q: "Food has NOT reached 70°F within the first 2 hours of cooling. What are your options?",
        c: ["Keep cooling it slowly overnight", "Reheat it to 165°F within 2 hours, or throw it out", "Put it in the freezer", "Serve it right away"], a: 1 },
      { q: "How deep should containers be when cooling food?",
        c: ["No more than 4 inches", "8 inches is fine", "Any depth — the pan doesn't matter", "At least 6 inches deep"], a: 0 },
      { q: "Which of these helps food cool faster and more evenly?",
        c: ["Covering it tightly with foil right away", "Leaving it on the counter all afternoon", "An ice-water bath with frequent stirring, or an ice paddle", "Stacking hot pans on top of each other"], a: 2 },
      { q: "When can cooling food be placed in the refrigerator?",
        c: ["Immediately at 135°F", "Once it reaches 70°F", "Only after it's fully frozen", "Never — food cools on the counter"], a: 1 },
      { q: "While food is actively cooling, it should be…",
        c: ["Covered loosely so heat can escape, with temps checked frequently", "Sealed airtight", "Left uncovered overnight", "Stirred once and forgotten"], a: 0 },
      { q: "What is the maximum use-by time for leftover foods stored in the refrigerator?",
        c: ["24 hours", "72 hours from first use", "1 week", "2 weeks"], a: 1 },
      { q: "After food is properly cooled below 41°F, what must be on the label?",
        c: ["Nothing — labels are optional", "Just the cook's name", "The contents and a use-by date", "Only the price"], a: 2 },
      { q: "Milk must be cold-held below what temperature?",
        c: ["55°F", "50°F", "45°F", "60°F"], a: 2 }
    ]
  },
  {
    n: 5,
    month: "May",
    title: "Food Storage, Labeling & Preventing Cross-Contamination",
    keyPoints: [
      "Store food at least 6 inches off the floor and 18 inches below the ceiling.",
      "Use FIFO — 'First In, First Out.' Older stock gets used first.",
      "Store raw and cooked foods separately. Raw meats go BELOW ready-to-eat foods, never above.",
      "Wash hands and change gloves between handling raw meat and ready-to-eat food.",
      "Label and date all stored food with contents and use-by date. Discard food past its date.",
      "Refrigerators hold at 41°F or below; temperatures are logged every shift.",
      "Cross-contamination happens when germs move from raw food, dirty hands, or dirty surfaces onto ready-to-eat food."
    ],
    questions: [
      { q: "How far off the floor must food be stored?",
        c: ["At least 6 inches", "2 inches", "Directly on a clean floor is fine", "1 inch on cardboard"], a: 0 },
      { q: "What does FIFO mean?",
        c: ["Freeze It, Forget It", "First In, First Out — use the oldest stock first", "Food In, Food Out", "Fresh Is Fine Only"], a: 1 },
      { q: "Where should raw chicken be stored in the refrigerator?",
        c: ["On the top shelf", "Next to the salads", "Below ready-to-eat foods, on a bottom shelf", "Anywhere there's space"], a: 2 },
      { q: "You just finished portioning raw meat and now need to slice sandwich bread. What must you do first?",
        c: ["Just change gloves — hands are fine", "Wipe hands on a dry towel", "Remove gloves, wash hands, and put on fresh gloves", "Nothing if you work quickly"], a: 2 },
      { q: "What belongs on the label of stored food?",
        c: ["Contents and use-by date", "Only the day of the week", "Nothing if you'll remember", "Just your initials"], a: 0 },
      { q: "You find a food item past its expiration/use-by date. What do you do?",
        c: ["Smell it — if it smells fine, use it", "Discard it", "Cook it extra long", "Move it to the freezer"], a: 1 },
      { q: "What temperature must refrigerators maintain?",
        c: ["41°F or below", "50°F or below", "Under 60°F", "32°F exactly"], a: 0 },
      { q: "Which is an example of cross-contamination?",
        c: ["Using separate cutting boards for raw meat and vegetables", "Raw meat juice dripping onto ready-to-eat food below it", "Washing hands between tasks", "Sanitizing the prep table"], a: 1 },
      { q: "How far below the ceiling must food be stored?",
        c: ["No limit — stack to the ceiling", "6 inches", "18 inches", "3 feet"], a: 2 },
      { q: "A delivery arrives with a badly dented, bulging can. What do you do?",
        c: ["Accept it — dents are cosmetic", "Reject/discard it per receiving guidelines", "Open it immediately to check", "Serve it first before it gets worse"], a: 1 }
    ]
  },
  {
    n: 6,
    month: "June",
    title: "Menu Management: Portion Control, Recipes & Substitutions",
    keyPoints: [
      "Follow standardized recipes exactly — they control nutrition, consistency, cost, and texture.",
      "Use the correct portioning tools (scoops, dippers, ladles) listed on the recipe and production sheet.",
      "The diet spreadsheet tells you which foods and portions each diet receives — follow it for every tray.",
      "Menu substitutions must be of similar nutritive value AND comply with each resident's diet order.",
      "Never change a resident's diet on your own — diet orders come from the physician.",
      "Record substitutions so there is a record of what was actually served.",
      "Plate presentation and palatability matter — food should look and taste appealing."
    ],
    questions: [
      { q: "Why must standardized recipes be followed exactly?",
        c: ["They are only suggestions", "They control nutrition, consistency, portion cost, and texture for every resident", "Only new cooks need recipes", "Recipes only matter for desserts"], a: 1 },
      { q: "What ensures each resident receives the correct serving size?",
        c: ["Estimating by eye", "Using the correct scoop, dipper, or ladle specified for the item", "Serving everyone extra", "Using whatever utensil is clean"], a: 1 },
      { q: "What does the diet spreadsheet tell you?",
        c: ["Employee schedules", "Which food items and portions each diet type receives", "Food prices", "Cleaning assignments"], a: 1 },
      { q: "A menu item runs out. The substitution you offer must be…",
        c: ["Whatever is fastest", "Anything the resident likes, regardless of diet", "Of similar nutritive value and allowed on the resident's diet order", "Always a sandwich"], a: 2 },
      { q: "Who can change a resident's diet order?",
        c: ["The physician (through the ordering process)", "Any cook", "The resident's roommate", "Whoever serves the tray"], a: 0 },
      { q: "When a substitution is made to the planned menu, what should happen?",
        c: ["Keep it secret", "It gets recorded so there's a record of what was served", "Nothing — substitutions don't matter", "Only tell the next shift verbally"], a: 1 },
      { q: "A resident on a physician-ordered mechanical soft diet asks for a regular-texture item. What do you do?",
        c: ["Serve it — the resident asked", "Follow the diet order and notify the nurse/manager about the resident's preference", "Ignore the request completely", "Change the diet yourself"], a: 1 },
      { q: "Why does plate presentation matter in a long-term care community?",
        c: ["It doesn't — taste is all that matters", "Appealing food supports appetite, intake, and quality of life", "Only for holiday meals", "Only for surveyors"], a: 1 },
      { q: "The production sheet for lunch tells you…",
        c: ["How much of each item to prepare and the portioning tool to use", "Who is off this weekend", "The weather forecast", "Resident room assignments"], a: 0 },
      { q: "Following the prescribed diet order for every tray protects residents from…",
        c: ["Nothing — diets are preferences", "Receiving food that could harm them (wrong texture, allergen, or restricted item)", "Getting too much variety", "Eating too slowly"], a: 1 }
    ]
  },
  {
    n: 7,
    month: "July",
    title: "Disaster & Emergency Preparedness for Dining Services",
    keyPoints: [
      "Know where your community's emergency plan and emergency menu are located.",
      "In an emergency, use food supplies in this order: perishable fresh foods → refrigerated foods → frozen foods → canned foods → enteral formulas.",
      "Check temperatures of refrigerated and frozen foods before serving. Discard any questionable food.",
      "Questionable water must be boiled or purified before use.",
      "Special diets and food allergies are STILL honored during an emergency.",
      "Emergency dishwashing (power outage or machine down): 3-sink method — wash in 120°F water with detergent, rinse in 120°F clean water, then chemical sanitizer.",
      "If there isn't enough water for handwashing/dishwashing, use disposable tableware from the emergency supply.",
      "The Dining Services Manager directs the department during a disaster."
    ],
    questions: [
      { q: "During an emergency, which food supplies are used FIRST?",
        c: ["Canned foods", "Frozen foods", "Perishable fresh foods", "Enteral formulas"], a: 2 },
      { q: "What is the correct order for using food supplies in an emergency?",
        c: ["Canned → frozen → fresh → refrigerated", "Perishable fresh → refrigerated → frozen → canned → enteral formulas", "Frozen → canned → fresh", "Any order is fine"], a: 1 },
      { q: "The water supply becomes questionable during a disaster. Before using it, you must…",
        c: ["Boil or purify it", "Filter it through a towel", "Use it quickly before it gets worse", "Add ice to it"], a: 0 },
      { q: "During a power outage, a refrigerated food's temperature is unknown and it looks questionable. What do you do?",
        c: ["Serve it fast", "Discard it", "Refreeze it", "Taste-test it"], a: 1 },
      { q: "Do special diets and food allergies still apply during an emergency?",
        c: ["No, all rules are suspended", "Only for some residents", "Yes — basic guidelines for special diets and allergies are still honored", "Only if the dietitian is in the building"], a: 2 },
      { q: "The dish machine is down. What is the first sink in the 3-sink emergency dishwashing method?",
        c: ["Sanitizer solution", "120°F water with adequate detergent (wash)", "Cold rinse water", "Bleach only"], a: 1 },
      { q: "In the 3-sink method, the third sink contains…",
        c: ["Soapy water", "Hot rinse water", "Chemical sanitizing solution", "Plain cold water"], a: 2 },
      { q: "There is not enough water for proper dishwashing. What do you use?",
        c: ["Disposable tableware from the emergency supply", "Lightly rinsed dishes", "Paper towels to wipe dishes", "The same dishes without washing"], a: 0 },
      { q: "Who is responsible for directing the Dining Services Department during a disaster?",
        c: ["Whoever arrives first", "The Dining Services Manager", "The maintenance director", "Each employee decides individually"], a: 1 },
      { q: "To use a fire extinguisher correctly, remember PASS. What does PASS stand for? (general fire safety)",
        c: ["Push, Alarm, Spray, Stop", "Pull the pin, Aim at the base, Squeeze the handle, Sweep side to side", "Point, Activate, Shake, Spray", "Pull, Aim at the flames' top, Squeeze, Stand still"], a: 1 }
    ]
  },
  {
    n: 8,
    month: "August",
    title: "Therapeutic Diets, Food Allergies & Thickened Liquids",
    keyPoints: [
      "Therapeutic diets and thickened liquids require a physician's order — always follow the diet order on the meal card.",
      "IDDSI thickness levels: Level 0 = Thin; Level 2 = Mildly Thick (nectar-like); Level 3 = Moderately Thick (honey-like); Level 4 = Extremely Thick (pudding-like).",
      "NEVER give thin liquids to a resident with a thickened liquid order — this is an aspiration risk.",
      "Report swallowing warning signs to the nurse: coughing during/after meals, wet or gurgling voice, watery eyes, food left in mouth, complaints of food getting stuck, drooling.",
      "Therapy reviews residents on thickened liquids at least every 3 months.",
      "Check the meal card for food allergies on EVERY tray — an allergen mistake can be life-threatening.",
      "If the wrong item is served to a resident with an allergy or a diet order, tell the nurse immediately."
    ],
    questions: [
      { q: "What is required before a resident is served thickened liquids?",
        c: ["A family request", "A physician's order stating the necessary consistency", "The cook's judgment", "Nothing — anyone can decide"], a: 1 },
      { q: "IDDSI Level 2 ('Mildly Thick') matches which older term?",
        c: ["Pudding-like", "Honey-like", "Nectar-like", "Thin"], a: 2 },
      { q: "IDDSI Level 3 ('Moderately Thick') matches which older term?",
        c: ["Honey-like", "Nectar-like", "Thin", "Spoon-thick"], a: 0 },
      { q: "IDDSI Level 4 ('Extremely Thick') matches which older term?",
        c: ["Nectar-like", "Thin", "Slightly thick", "Pudding-like / spoon-thick"], a: 3 },
      { q: "A resident with a thickened-liquid order asks for a regular glass of water. What do you do?",
        c: ["Give it — water is harmless", "Never serve thin liquids against the order; offer the ordered consistency and tell the nurse about the request", "Give half a glass", "Add ice so it's colder"], a: 1 },
      { q: "Which of these is a warning sign of swallowing problems you must report to the nurse?",
        c: ["Coughing during or after meals, or a wet gurgling voice", "Eating quickly", "Asking for seconds", "Preferring cold foods"], a: 0 },
      { q: "How often does therapy review residents receiving thickened liquids?",
        c: ["Once a year", "At least every 3 months, or sooner on staff request", "Only when problems occur", "Never after the first screen"], a: 1 },
      { q: "Before serving any tray, how do you know if a resident has a food allergy?",
        c: ["Guess based on the resident's age", "Check the meal card / tray card for every tray", "Ask the resident's roommate", "Allergies are only nursing's job"], a: 1 },
      { q: "You realize a resident with a milk allergy was just served pudding made with milk. What do you do?",
        c: ["Take the pudding back quietly", "Tell the nurse immediately so the resident can be monitored", "Wait to see if they eat it", "Nothing — one serving is fine"], a: 1 },
      { q: "Why does dining services follow physician-ordered therapeutic diets exactly?",
        c: ["To reduce food costs", "Habit and tradition", "The wrong food, texture, or liquid can cause serious harm such as choking or aspiration", "To simplify the menu"], a: 2 }
    ]
  },
  {
    n: 9,
    month: "September",
    title: "Workplace Safety: Knives, Burns, Slips & Chemicals",
    keyPoints: [
      "A sharp knife, used thoughtfully, is SAFER than a dull knife. Use the correct knife for the job.",
      "Always cut on a cutting board — never hold food in your hand. Carry knives point down.",
      "Never leave knives soaking in a sink or in dishwater. Store knives in racks or slots.",
      "Handle hot items only with DRY cloths, mitts, or pot holders. Lift lids away from you so steam escapes safely.",
      "Broken glass or china: sweep with a dustpan and brush, use a dampened paper towel for slivers, and put pieces in a special container — never in regular trash bags or bare hands.",
      "Clean up spills immediately and use wet floor signs to prevent slips, trips, and falls.",
      "Follow label directions for chemicals; never mix chemicals; store them per facility guidelines.",
      "Report every accident and every cut — even the slightest — and get treatment."
    ],
    questions: [
      { q: "Which is safer to use?",
        c: ["A dull knife — it can't cut you", "A sharp knife used effectively and thoughtfully", "Any knife used quickly", "A knife with a loose handle"], a: 1 },
      { q: "Where should knives NEVER be left?",
        c: ["In a knife rack", "In a drawer slot", "Soaking in a sink or dishwater", "On a magnetic strip"], a: 2 },
      { q: "How do you carry a knife through the kitchen?",
        c: ["Blade up", "Point down", "In your apron pocket", "Behind your back"], a: 1 },
      { q: "When cutting food you should always…",
        c: ["Hold the food in your hand", "Use a cutting board", "Cut toward your body", "Use the sharpest knife for every job regardless of task"], a: 1 },
      { q: "A glass breaks near the prep area. How do you clean it up?",
        c: ["Pick up all pieces with bare hands", "Sweep with dustpan and brush, use a damp paper towel for slivers, and put pieces in a special container", "Kick pieces out of the walkway", "Put the glass in a regular trash bag"], a: 1 },
      { q: "Why must cloths and pot holders be DRY when handling hot pans?",
        c: ["Wet cloth transmits heat and steam and can burn you", "Dry cloths look more professional", "Wet cloths leave streaks", "It doesn't matter"], a: 0 },
      { q: "How do you remove a lid from a hot pot safely?",
        c: ["Lean over and lift straight up", "Lift it so steam escapes away from your hands and face", "Remove it with wet fingers", "Shake the pot first"], a: 1 },
      { q: "You get a small cut on your finger. It barely bleeds. What do you do?",
        c: ["Ignore it — it's minor", "Report it and get treatment, even for the slightest cut, then cover it before returning to work", "Rinse and keep working", "Wait until end of shift"], a: 1 },
      { q: "What is the rule about mixing cleaning chemicals?",
        c: ["Mixing makes them stronger", "Never mix chemicals — follow label directions", "Only mix bleach and ammonia", "Mixing is fine in small amounts"], a: 1 },
      { q: "You see liquid spilled on the kitchen floor. What do you do?",
        c: ["Step over it and keep working", "Clean it up immediately and use a wet floor sign", "Wait for housekeeping", "Cover it with a towel and leave it"], a: 1 }
    ]
  },
  {
    n: 10,
    month: "October",
    title: "Sanitation: Dish Machine, 3-Compartment Sink & Sanitizers",
    keyPoints: [
      "3-compartment sink: (1) WASH in 120°F water with detergent, (2) RINSE in clean 120°F water, (3) SANITIZE in chemical solution.",
      "Chlorine (bleach) sanitizer for food-contact surfaces: 50–100 ppm — about 1 tablespoon of bleach per gallon of water; minimum 10-second immersion.",
      "Quaternary (QAC) sanitizer: 150–200 ppm, per manufacturer's contact time. Hot-water sanitizing: at least 171°F for 30 seconds.",
      "Test sanitizer with test strips before use, and test dispensers at least daily.",
      "High-temp dish machines: 150°F wash / 180°F final rinse. Low-temp: 120°F wash + 50 ppm chlorine.",
      "AIR DRY everything — towel-drying dishes and utensils spreads contamination.",
      "Wiping cloths are stored submerged in sanitizer solution between uses.",
      "Store cleaned utensils and equipment at least 6 inches off the floor, covered or inverted, protected from splash and dust."
    ],
    questions: [
      { q: "What is the correct order for the 3-compartment sink?",
        c: ["Sanitize, wash, rinse", "Wash, rinse, sanitize", "Rinse, sanitize, wash", "Wash, sanitize, dry"], a: 1 },
      { q: "What is the correct chlorine (bleach) sanitizer concentration for food-contact surfaces?",
        c: ["50–100 ppm", "5–10 ppm", "600 ppm", "1,000 ppm"], a: 0 },
      { q: "How do you make a bleach sanitizing solution for food-contact surfaces?",
        c: ["1 cup bleach per gallon of water", "About 1 tablespoon bleach per gallon of water", "Half bleach, half water", "A splash of bleach in a full sink"], a: 1 },
      { q: "How do you verify your sanitizer is at the right strength?",
        c: ["Smell it", "Check the color", "Test it with a test strip/tape before use", "Trust the dispenser without checking"], a: 2 },
      { q: "What temperature should the wash water be in the 3-compartment sink?",
        c: ["120°F", "70°F", "180°F", "Any temperature"], a: 0 },
      { q: "For hot-water sanitizing by immersion, water must be at least…",
        c: ["120°F for 10 seconds", "140°F for 1 minute", "171°F for 30 seconds", "212°F (boiling)"], a: 2 },
      { q: "What final rinse temperature does a high-temp dish machine need?",
        c: ["120°F", "150°F", "180°F", "200°F"], a: 2 },
      { q: "After washing and sanitizing, how should dishes and utensils be dried?",
        c: ["With a clean towel", "Air dry — never towel dry", "With paper towels", "With a fan blowing from the dirty dish area"], a: 1 },
      { q: "Between uses, wiping cloths used for sanitizing should be…",
        c: ["Draped over the faucet", "In your apron pocket", "Kept submerged in sanitizer solution", "Left on the prep table"], a: 2 },
      { q: "Quaternary (QAC) sanitizer should be used at what concentration?",
        c: ["150–200 ppm, per manufacturer's instructions", "10–20 ppm", "600+ ppm", "Whatever looks sudsy"], a: 0 }
    ]
  },
  {
    n: 11,
    month: "November",
    title: "Infection Control: Employee Illness, PPE & Isolation Trays",
    keyPoints: [
      "Handwashing is the single most important way to prevent the spread of infection.",
      "Stay home and notify your supervisor if you have nausea, vomiting, diarrhea, or fever — ill food workers can cause foodborne illness outbreaks.",
      "Follow your community's policy for PPE (masks, gloves, gowns) and posted precaution signs.",
      "Residents in isolation are served with DISPOSABLE tableware only.",
      "Nursing staff (not dining) dispose of isolation tableware according to the facility's isolation procedure.",
      "Keep cuts and sores covered. Notify your supervisor of exposure to contagious illness.",
      "Sanitizing (50–100 ppm) is for food-contact surfaces; disinfecting (600+ ppm, about ¼ cup bleach per gallon) is for common areas like door knobs, light switches, and carts."
    ],
    questions: [
      { q: "What is the single most important way to prevent the spread of infection?",
        c: ["Wearing two pairs of gloves", "Proper handwashing", "Spraying air freshener", "Wiping hands on a clean apron"], a: 1 },
      { q: "You have diarrhea and vomiting. Can you work with food today?",
        c: ["Yes, if you feel okay", "Yes, with gloves on", "No — report your illness to your supervisor and stay out of food handling per policy", "Yes, if you're scheduled"], a: 2 },
      { q: "Why are ill food workers such a risk in a nursing facility?",
        c: ["They work more slowly", "They can spread foodborne illness to frail residents, causing serious outbreaks", "They use more supplies", "They aren't a risk"], a: 1 },
      { q: "How are residents in isolation served their meals?",
        c: ["With regular dishes washed separately", "With disposable tableware only", "With any available dishes", "They don't receive trays"], a: 1 },
      { q: "Who disposes of tableware from an isolation room?",
        c: ["Dining services picks it up as usual", "The resident", "Nursing personnel, following the facility's isolation procedure", "Housekeeping puts it back in the kitchen"], a: 2 },
      { q: "When must PPE (mask, gown, gloves) be worn?",
        c: ["Only during flu season", "As required by your community's policy and posted precaution signs", "Never in dining services", "Only when you feel sick"], a: 1 },
      { q: "What concentration of bleach solution is used to DISINFECT common areas like door knobs and carts?",
        c: ["600+ ppm — about ¼ cup bleach per gallon of water", "50 ppm", "10 ppm", "Plain water"], a: 0 },
      { q: "What's the difference between sanitizing and disinfecting?",
        c: ["They're the same", "Sanitizing (50–100 ppm) is for food-contact surfaces; disinfecting (600+ ppm) is for common areas — never on food surfaces without rinsing", "Disinfecting is weaker", "Sanitizing is only for floors"], a: 1 },
      { q: "You were exposed to someone with a contagious illness. What should you do?",
        c: ["Keep it to yourself", "Notify your direct supervisor per community policy", "Only mention it if you feel sick later", "Post about it in the break room"], a: 1 },
      { q: "An open sore on your arm should be…",
        c: ["Left open to the air while cooking", "Properly covered, and reported to your supervisor", "Covered only for surveys", "Ignored if it doesn't hurt"], a: 1 }
    ]
  },
  {
    n: 12,
    month: "December",
    title: "Dining With Dignity: Preferences, Adaptive Equipment & Dementia Mealtime",
    keyPoints: [
      "Honor resident food preferences — dining is one of the most important parts of a resident's day.",
      "Adaptive equipment (plate guards, special cups, built-up utensils, sporks) must be provided as care-planned so residents can eat as independently as possible.",
      "Restrictive therapeutic diets are generally avoided for residents with dementia or poor appetite — a liberalized diet supports intake and quality of life.",
      "For residents with dementia: reduce distractions, offer simple choices, give gentle cues, and allow plenty of time. Never rush a resident.",
      "All tableware must be in good condition — free of chips, cracks, and stains.",
      "If a resident refuses food, respect their choice and offer a substitute of similar nutritive value.",
      "Report eating changes (eating less, taking longer, leaving food) to the nurse so the care team can respond.",
      "Food brought in by visitors is handled according to your community's policy — know it and follow it."
    ],
    questions: [
      { q: "Why do resident food preferences matter so much?",
        c: ["They don't — the menu is fixed", "Meals are central to residents' dignity, satisfaction, and quality of life", "Only for private-pay residents", "Preferences only matter on holidays"], a: 1 },
      { q: "A resident's care plan lists a plate guard and built-up utensils. What do you do?",
        c: ["Provide them with every meal so the resident can eat independently", "Provide them only when the resident asks", "Save them for special occasions", "Adaptive equipment is optional"], a: 0 },
      { q: "For residents with dementia or poor appetite, restrictive diets are generally…",
        c: ["Made stricter", "Required by law", "Avoided — a liberalized diet supports better intake and quality of life", "Doubled up"], a: 2 },
      { q: "Which approach helps a resident with dementia at mealtime?",
        c: ["Loud music and lots of activity", "Rushing them so food stays hot", "Reduced distractions, simple choices, gentle cues, and plenty of time", "Removing the tray after 10 minutes"], a: 2 },
      { q: "You notice a dinner plate with a chip in the rim. What do you do?",
        c: ["Use it — chips add character", "Remove it from service — tableware must be free of chips, cracks, and stains", "Turn the chip away from the resident", "Save it for staff meals"], a: 1 },
      { q: "A resident refuses their vegetable. The respectful response is to…",
        c: ["Insist they eat it", "Respect the choice and offer a substitute of similar nutritive value", "Take away the whole tray", "Tell them there are no other options"], a: 1 },
      { q: "A resident who usually finishes meals has been leaving most of their food this week. What do you do?",
        c: ["Nothing — appetites vary", "Report the change to the nurse so the care team can follow up", "Serve smaller portions so it's less obvious", "Wait a month to see"], a: 1 },
      { q: "A family member brings homemade food for a resident. What guides how it's handled?",
        c: ["The community's policy on food brought in by visitors", "There are no rules for visitor food", "It must always be thrown away", "It goes in the walk-in with kitchen stock, unlabeled"], a: 0 },
      { q: "Which practice supports dignity during dining service?",
        c: ["Addressing residents by name and never rushing them", "Standing over residents while they eat", "Talking about residents in front of them", "Serving whoever is quietest first"], a: 0 },
      { q: "Sporks, special drinking cups, and plate guard devices are examples of…",
        c: ["Optional luxury items", "Adaptive equipment that helps residents eat as independently as possible", "Equipment only used in the hospital", "Items only therapy can touch"], a: 1 }
    ]
  }
];
